### ISSUE TITLE
El dataset de 100 Hs en formato LJSpeech ha sido eliminado!

### ISSUE THREAD

**Issue by Mixomo** [carlfm01/my-speech-datasets#2]
¡Hola! ¡Tus datasets son referentes en las investigaciones de TTS desde hace años!
Hace tiempo quise acceder nuevamente al dataset de 100 horas en formato LJSpeech, pero había sido removido de Google Drive.
¿Fue una decisión tuya, o Google lo eliminó de sus servidores?
¡Muchas gracias!

**Comment by carlfm01** [comment]
Hola, gracias por el reporte, no he sido yo, voy a revisar que ha pasado.

**Comment by carlfm01** [comment]
Perdón por la demora ¿es este mismo https://www.kaggle.com/datasets/carlfm01/120h-spanish-speech? Parece que si lo eliminaron porque no lo encuentro.

**Comment by Mixomo** [comment]
> Perdón por la demora ¿es este mismo https://www.kaggle.com/datasets/carlfm01/120h-spanish-speech? Parece que si lo eliminaron porque no lo encuentro.

Claro,no. No es ese. El dataset se llamaba tux_100 y tenía 100 horas con 50 horas validadas.

**Comment by justinjohn0306** [comment]
@carlfm01 I think it is this link that has expired: https://drive.google.com/file/d/1Sm_zyBo67XHkiFhcRSQ4YaHPYM0slO_e/view?usp=sharing

**Comment by carlfm01** [comment]
> > Perdón por la demora ¿es este mismo https://www.kaggle.com/datasets/carlfm01/120h-spanish-speech? Parece que si lo eliminaron porque no lo encuentro.
> 
> Claro,no. No es ese. El dataset se llamaba tux_100 y tenía 100 horas con 50 horas validadas.

Perdón por la demora, hoy voy a revisar en mis discos buscando este set, espero poder encontrarlo para subirlo.

**Comment by carlfm01** [comment]
> @carlfm01 I think it is this link that has expired: https://drive.google.com/file/d/1Sm_zyBo67XHkiFhcRSQ4YaHPYM0slO_e/view?usp=sharing

Thank you.

**Comment by carlfm01** [comment]
Revisé algunos discos sin suerte ¿no recuerdan el nombre del .zip?

**Comment by justinjohn0306** [comment]
> Revisé algunos discos sin suerte ¿no recuerdan el nombre del .zip?

tux-100h.zip

**Comment by Mixomo** [comment]
Este fue tu posteo en common voice en su época: 

https://discourse.mozilla.org/t/sharing-my-100h-of-single-speaker-spanish/45288

**Comment by carlfm01** [comment]
Me ha tomado tiempo revisar 10 discos entre ellos mecánicos, pero encontré un archivo que puede ser ¿es este https://carlos-shr.s3.amazonaws.com/tux-100h.zip? @Mixomo

**Comment by Mixomo** [comment]
> Me ha tomado tiempo revisar 10 discos entre ellos mecánicos, pero encontré un archivo que puede ser ¿es este https://carlos-shr.s3.amazonaws.com/tux-100h.zip? @Mixomo

Sí, es ese! Muchísimas gracias por tomarte el tiempo de recuperarlo! Abrazo!

**Comment by carlfm01** [comment]
Un gusto.
